export enum ContentType {
  JSON = "application/json",
  HTML = "text/html",
  PLAIN = "text/plain",
  XML = "application/xml",
  FORM = "application/x-www-form-urlencoded",
  FORM_DATA = "multipart/form-data",
  JAVASCRIPT = "application/javascript",
  CSS = "text/css",
  CSV = "text/csv",
  PDF = "application/pdf",
  PNG = "image/png",
  JPEG = "image/jpeg",
  GIF = "image/gif",
  SVG = "image/svg+xml",
  ICO = "image/x-icon",
  MP3 = "audio/mpeg",
  MP4 = "video/mp4",
  WEBM = "video/webm",
}
